services:
  - type: web
    name: projet-pdfbox
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ORB_INITIAL_HOST
        value: localhost
        scope: runtime
      - key: ORB_INITIAL_PORT
        value: "1050"
        scope: runtime
    plan: free
    region: oregon
    autoDeploy: true
