# Application Name
spring.application.name=pdfapi

# Server Configuration
server.port=8080

# Spring JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:pdfdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (optional - for development only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Configuration
app.jwtSecret=SecretKeyForJWTTokenPdfServiceSecretKeyForJWTTokenPdfService123456
app.jwtExpirationMs=86400000

# Logging
logging.level.root=INFO
logging.level.com.babacar.pdfapi=DEBUG

# CORBA Configuration
org.omg.CORBA.ORBInitialHost=${ORB_INITIAL_HOST:localhost}
org.omg.CORBA.ORBInitialPort=${ORB_INITIAL_PORT:1050}
