package CalculatriceApp;


/**
* CalculatriceApp/DivisionParZeroException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 35 UTC
*/

public final class DivisionParZeroException extends org.omg.CORBA.UserException
{
  public String message = null;

  public DivisionParZeroException ()
  {
    super(DivisionParZeroExceptionHelper.id());
  } // ctor

  public DivisionParZeroException (String _message)
  {
    super(DivisionParZeroExceptionHelper.id());
    message = _message;
  } // ctor


  public DivisionParZeroException (String $reason, String _message)
  {
    super(DivisionParZeroExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class DivisionParZeroException
