package CalculatriceApp;

/**
* CalculatriceApp/PdfServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 35 UTC
*/


/**
   * Interface principale PDF
   * Les entrées/sorties PDF sont transmises en base64 (string).
   */
public final class PdfServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.PdfService value = null;

  public PdfServiceHolder ()
  {
  }

  public PdfServiceHolder (CalculatriceApp.PdfService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.PdfServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.PdfServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.PdfServiceHelper.type ();
  }

}
