package CalculatriceApp;


/**
* CalculatriceApp/PdfServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 35 UTC
*/


/**
   * Interface principale PDF
   * Les entrées/sorties PDF sont transmises en base64 (string).
   */
public abstract class PdfServicePOA extends org.omg.PortableServer.Servant
 implements CalculatriceApp.PdfServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fusionPdf", new java.lang.Integer (0));
    _methods.put ("decoupagePdf", new java.lang.Integer (1));
    _methods.put ("extractionPage", new java.lang.Integer (2));
    _methods.put ("suppressionPage", new java.lang.Integer (3));
    _methods.put ("ajoutMotDePasse", new java.lang.Integer (4));
    _methods.put ("conversionPdfEnImage", new java.lang.Integer (5));
    _methods.put ("extractionTexte", new java.lang.Integer (6));
    _methods.put ("creationPdf", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /** Fusionne 2 PDFs (input1 + input2) -> pdfBase64Out */
       case 0:  // CalculatriceApp/PdfService/fusionPdf
       {
         String pdfBase64_1 = in.read_string ();
         String pdfBase64_2 = in.read_string ();
         CalculatriceApp.ResultatPdf $result = null;
         $result = this.fusionPdf (pdfBase64_1, pdfBase64_2);
         out = $rh.createReply();
         CalculatriceApp.ResultatPdfHelper.write (out, $result);
         break;
       }


  /** Découpe un PDF en une nouvelle sortie contenant uniquement la plage */
       case 1:  // CalculatriceApp/PdfService/decoupagePdf
       {
         String pdfBase64 = in.read_string ();
         CalculatriceApp.PlagePages plage = CalculatriceApp.PlagePagesHelper.read (in);
         CalculatriceApp.ResultatPdf $result = null;
         $result = this.decoupagePdf (pdfBase64, plage);
         out = $rh.createReply();
         CalculatriceApp.ResultatPdfHelper.write (out, $result);
         break;
       }


  /** Extraction d'une page (plage d'une page) -> nouveau PDF */
       case 2:  // CalculatriceApp/PdfService/extractionPage
       {
         String pdfBase64 = in.read_string ();
         CalculatriceApp.PlagePages plage = CalculatriceApp.PlagePagesHelper.read (in);
         CalculatriceApp.ResultatPdf $result = null;
         $result = this.extractionPage (pdfBase64, plage);
         out = $rh.createReply();
         CalculatriceApp.ResultatPdfHelper.write (out, $result);
         break;
       }


  /** Suppression des pages (définies par plage) -> PDF résultat */
       case 3:  // CalculatriceApp/PdfService/suppressionPage
       {
         String pdfBase64 = in.read_string ();
         CalculatriceApp.PlagePages plage = CalculatriceApp.PlagePagesHelper.read (in);
         CalculatriceApp.ResultatPdf $result = null;
         $result = this.suppressionPage (pdfBase64, plage);
         out = $rh.createReply();
         CalculatriceApp.ResultatPdfHelper.write (out, $result);
         break;
       }


  /** Ajoute un mot de passe : protection du PDF en sortie */
       case 4:  // CalculatriceApp/PdfService/ajoutMotDePasse
       {
         String pdfBase64 = in.read_string ();
         String password = in.read_string ();
         CalculatriceApp.ResultatPdf $result = null;
         $result = this.ajoutMotDePasse (pdfBase64, password);
         out = $rh.createReply();
         CalculatriceApp.ResultatPdfHelper.write (out, $result);
         break;
       }


  /** Convertit PDF -> image(s) (PNG)
     * Simplification TP : renvoie base64 du premier rendu (page 1).
     * Le champ nomFichierSortie contiendra par ex. "image1.png".
     */
       case 5:  // CalculatriceApp/PdfService/conversionPdfEnImage
       {
         String pdfBase64 = in.read_string ();
         int dpi = in.read_long ();
         CalculatriceApp.ResultatPdf $result = null;
         $result = this.conversionPdfEnImage (pdfBase64, dpi);
         out = $rh.createReply();
         CalculatriceApp.ResultatPdfHelper.write (out, $result);
         break;
       }


  /** Extrait le texte d'un PDF (retourne texte directement dans message + succes=true) */
       case 6:  // CalculatriceApp/PdfService/extractionTexte
       {
         String pdfBase64 = in.read_string ();
         CalculatriceApp.ResultatPdf $result = null;
         $result = this.extractionTexte (pdfBase64);
         out = $rh.createReply();
         CalculatriceApp.ResultatPdfHelper.write (out, $result);
         break;
       }


  /** Crée un PDF depuis un texte donné */
       case 7:  // CalculatriceApp/PdfService/creationPdf
       {
         String texte = in.read_string ();
         CalculatriceApp.ResultatPdf $result = null;
         $result = this.creationPdf (texte);
         out = $rh.createReply();
         CalculatriceApp.ResultatPdfHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculatriceApp/PdfService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PdfService _this() 
  {
    return PdfServiceHelper.narrow(
    super._this_object());
  }

  public PdfService _this(org.omg.CORBA.ORB orb) 
  {
    return PdfServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PdfServicePOA
