package CalculatriceApp;

/**
* CalculatriceApp/DivisionParZeroExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* vendredi 8 mai 2026 00 h 56 UTC
*/

public final class DivisionParZeroExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.DivisionParZeroException value = null;

  public DivisionParZeroExceptionHolder ()
  {
  }

  public DivisionParZeroExceptionHolder (CalculatriceApp.DivisionParZeroException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.DivisionParZeroExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.DivisionParZeroExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.DivisionParZeroExceptionHelper.type ();
  }

}
