package CalculatriceApp;


/**
* CalculatriceApp/OperationNonSupporteeException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* vendredi 8 mai 2026 00 h 56 UTC
*/

public final class OperationNonSupporteeException extends org.omg.CORBA.UserException
{
  public String operation = null;

  // Nom de l'opération
  public String raison = null;

  public OperationNonSupporteeException ()
  {
    super(OperationNonSupporteeExceptionHelper.id());
  } // ctor

  public OperationNonSupporteeException (String _operation, String _raison)
  {
    super(OperationNonSupporteeExceptionHelper.id());
    operation = _operation;
    raison = _raison;
  } // ctor


  public OperationNonSupporteeException (String $reason, String _operation, String _raison)
  {
    super(OperationNonSupporteeExceptionHelper.id() + "  " + $reason);
    operation = _operation;
    raison = _raison;
  } // ctor

} // class OperationNonSupporteeException
