package CalculatriceApp;

/**
* CalculatriceApp/OperationNonSupporteeExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 20 UTC
*/

public final class OperationNonSupporteeExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.OperationNonSupporteeException value = null;

  public OperationNonSupporteeExceptionHolder ()
  {
  }

  public OperationNonSupporteeExceptionHolder (CalculatriceApp.OperationNonSupporteeException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.OperationNonSupporteeExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.OperationNonSupporteeExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.OperationNonSupporteeExceptionHelper.type ();
  }

}
