package CalculatriceApp;


/**
* CalculatriceApp/PdfServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 20 UTC
*/


/**
   * Interface principale PDF
   * Les entrées/sorties PDF sont transmises en base64 (string).
   */
public interface PdfServiceOperations 
{

  /** Fusionne 2 PDFs (input1 + input2) -> pdfBase64Out */
  CalculatriceApp.ResultatPdf fusionPdf (String pdfBase64_1, String pdfBase64_2);

  /** Découpe un PDF en une nouvelle sortie contenant uniquement la plage */
  CalculatriceApp.ResultatPdf decoupagePdf (String pdfBase64, CalculatriceApp.PlagePages plage);

  /** Extraction d'une page (plage d'une page) -> nouveau PDF */
  CalculatriceApp.ResultatPdf extractionPage (String pdfBase64, CalculatriceApp.PlagePages plage);

  /** Suppression des pages (définies par plage) -> PDF résultat */
  CalculatriceApp.ResultatPdf suppressionPage (String pdfBase64, CalculatriceApp.PlagePages plage);

  /** Ajoute un mot de passe : protection du PDF en sortie */
  CalculatriceApp.ResultatPdf ajoutMotDePasse (String pdfBase64, String password);

  /** Convertit PDF -> image(s) (PNG)
     * Simplification TP : renvoie base64 du premier rendu (page 1).
     * Le champ nomFichierSortie contiendra par ex. "image1.png".
     */
  CalculatriceApp.ResultatPdf conversionPdfEnImage (String pdfBase64, int dpi);

  /** Extrait le texte d'un PDF (retourne texte directement dans message + succes=true) */
  CalculatriceApp.ResultatPdf extractionTexte (String pdfBase64);

  /** Crée un PDF depuis un texte donné */
  CalculatriceApp.ResultatPdf creationPdf (String texte);
} // interface PdfServiceOperations
