package CalculatriceApp;


/**
* CalculatriceApp/PdfService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* vendredi 8 mai 2026 00 h 56 UTC
*/


/**
   * Interface principale PDF
   * Les entrées/sorties PDF sont transmises en base64 (string).
   */
public interface PdfService extends PdfServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PdfService
