package CalculatriceApp;


/**
* CalculatriceApp/PlagePages.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* vendredi 8 mai 2026 00 h 56 UTC
*/

public final class PlagePages implements org.omg.CORBA.portable.IDLEntity
{
  public int debut = (int)0;

  // incluse
  public int fin = (int)0;

  public PlagePages ()
  {
  } // ctor

  public PlagePages (int _debut, int _fin)
  {
    debut = _debut;
    fin = _fin;
  } // ctor

} // class PlagePages
