package CalculatriceApp;

/**
* CalculatriceApp/PlagePagesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 20 UTC
*/

public final class PlagePagesHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.PlagePages value = null;

  public PlagePagesHolder ()
  {
  }

  public PlagePagesHolder (CalculatriceApp.PlagePages initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.PlagePagesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.PlagePagesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.PlagePagesHelper.type ();
  }

}
