package CalculatriceApp;


/**
* CalculatriceApp/ResultatPdf.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 20 UTC
*/

public final class ResultatPdf implements org.omg.CORBA.portable.IDLEntity
{
  public boolean succes = false;

  // true si OK
  public String message = null;

  // message d'état / erreur
  public String nomFichierSortie = null;

  public ResultatPdf ()
  {
  } // ctor

  public ResultatPdf (boolean _succes, String _message, String _nomFichierSortie)
  {
    succes = _succes;
    message = _message;
    nomFichierSortie = _nomFichierSortie;
  } // ctor

} // class ResultatPdf
