package CalculatriceApp;

/**
* CalculatriceApp/ResultatPdfHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* vendredi 8 mai 2026 00 h 56 UTC
*/

public final class ResultatPdfHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.ResultatPdf value = null;

  public ResultatPdfHolder ()
  {
  }

  public ResultatPdfHolder (CalculatriceApp.ResultatPdf initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.ResultatPdfHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.ResultatPdfHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.ResultatPdfHelper.type ();
  }

}
