package CalculatriceApp;

/**
* CalculatriceApp/ResultatCalculHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 20 UTC
*/

public final class ResultatCalculHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.ResultatCalcul value = null;

  public ResultatCalculHolder ()
  {
  }

  public ResultatCalculHolder (CalculatriceApp.ResultatCalcul initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.ResultatCalculHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.ResultatCalculHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.ResultatCalculHelper.type ();
  }

}
