package CalculatriceApp;


/**
* CalculatriceApp/TypeOperation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* vendredi 8 mai 2026 00 h 56 UTC
*/


/**
   * �0numération des opérations disponibles
   */
public class TypeOperation implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static CalculatriceApp.TypeOperation[] __array = new CalculatriceApp.TypeOperation [__size];

  public static final int _ADDITION = 0;
  public static final CalculatriceApp.TypeOperation ADDITION = new CalculatriceApp.TypeOperation(_ADDITION);
  public static final int _SOUSTRACTION = 1;
  public static final CalculatriceApp.TypeOperation SOUSTRACTION = new CalculatriceApp.TypeOperation(_SOUSTRACTION);
  public static final int _MULTIPLICATION = 2;
  public static final CalculatriceApp.TypeOperation MULTIPLICATION = new CalculatriceApp.TypeOperation(_MULTIPLICATION);
  public static final int _DIVISION = 3;
  public static final CalculatriceApp.TypeOperation DIVISION = new CalculatriceApp.TypeOperation(_DIVISION);
  public static final int _MODULO = 4;
  public static final CalculatriceApp.TypeOperation MODULO = new CalculatriceApp.TypeOperation(_MODULO);
  public static final int _PUISSANCE = 5;
  public static final CalculatriceApp.TypeOperation PUISSANCE = new CalculatriceApp.TypeOperation(_PUISSANCE);

  public int value ()
  {
    return __value;
  }

  public static CalculatriceApp.TypeOperation from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TypeOperation (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TypeOperation
