package CalculatriceApp;


/**
* CalculatriceApp/_CalculatriceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 35 UTC
*/


/**
   * Interface principale : Calculatrice
   * 
   * Fournit des opérations mathématiques variées
   * sur deux nombres flottants
   */
public class _CalculatriceStub extends org.omg.CORBA.portable.ObjectImpl implements CalculatriceApp.Calculatrice
{


  /**
     * Effectue l'addition de deux nombres
     * @param a Premier opérande
     * @param b Deuxième opérande
     * @return Le résultat de a + b
     */
  public double add (double a, double b)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("add", true);
                $out.write_double (a);
                $out.write_double (b);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return add (a, b        );
            } finally {
                _releaseReply ($in);
            }
  } // add


  /**
     * Effectue la soustraction
     * @param a Minuende
     * @param b Soustrahende
     * @return Le résultat de a - b
     */
  public double substract (double a, double b)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("substract", true);
                $out.write_double (a);
                $out.write_double (b);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return substract (a, b        );
            } finally {
                _releaseReply ($in);
            }
  } // substract


  /**
     * Effectue la multiplication
     * @param a Premier facteur
     * @param b Deuxième facteur
     * @return Le résultat de a * b
     */
  public double multiply (double a, double b)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("multiply", true);
                $out.write_double (a);
                $out.write_double (b);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return multiply (a, b        );
            } finally {
                _releaseReply ($in);
            }
  } // multiply


  /**
     * Effectue la division avec vérification
     * @param numerateur Dividende
     * @param denominateur Diviseur
     * @return Le résultat de numerateur / denominateur
     * @throws DivisionParZeroException si denominateur == 0
     */
  public double divide (double numerateur, double denominateur) throws CalculatriceApp.DivisionParZeroException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("divide", true);
                $out.write_double (numerateur);
                $out.write_double (denominateur);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CalculatriceApp/DivisionParZeroException:1.0"))
                    throw CalculatriceApp.DivisionParZeroExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return divide (numerateur, denominateur        );
            } finally {
                _releaseReply ($in);
            }
  } // divide


  /**
     * Calcule le modulo (reste de la division entière)
     * @param dividende Premier nombre
     * @param diviseur Deuxième nombre
     * @return Le reste de la division
     * @throws DivisionParZeroException si diviseur == 0
     */
  public int modulo (int dividende, int diviseur) throws CalculatriceApp.DivisionParZeroException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modulo", true);
                $out.write_long (dividende);
                $out.write_long (diviseur);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CalculatriceApp/DivisionParZeroException:1.0"))
                    throw CalculatriceApp.DivisionParZeroExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return modulo (dividende, diviseur        );
            } finally {
                _releaseReply ($in);
            }
  } // modulo


  /**
     * Calcule la puissance (base ^ exposant)
     * @param base La base
     * @param exposant L'exposant (doit etre >= 0)
     * @return base ^ exposant
     */
  public double power (double base, int exposant)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("power", true);
                $out.write_double (base);
                $out.write_long (exposant);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return power (base, exposant        );
            } finally {
                _releaseReply ($in);
            }
  } // power


  /**
     * Opération générique avec type d'opération comme paramètre
     * Permet de tester différentes opérations dynamiquement
     * @param operation Le type d'opération à effectuer
     * @param a Premier opérande
     * @param b Deuxième opérande
     * @return Structure contenant le résultat et les métadonnées
     * @throws DivisionParZeroException si division par zéro
     * @throws OperationNonSupporteeException si opération invalide
     */
  public CalculatriceApp.ResultatCalcul operationGenerique (CalculatriceApp.TypeOperation operation, double a, double b) throws CalculatriceApp.DivisionParZeroException, CalculatriceApp.OperationNonSupporteeException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("operationGenerique", true);
                CalculatriceApp.TypeOperationHelper.write ($out, operation);
                $out.write_double (a);
                $out.write_double (b);
                $in = _invoke ($out);
                CalculatriceApp.ResultatCalcul $result = CalculatriceApp.ResultatCalculHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CalculatriceApp/DivisionParZeroException:1.0"))
                    throw CalculatriceApp.DivisionParZeroExceptionHelper.read ($in);
                else if (_id.equals ("IDL:CalculatriceApp/OperationNonSupporteeException:1.0"))
                    throw CalculatriceApp.OperationNonSupporteeExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return operationGenerique (operation, a, b        );
            } finally {
                _releaseReply ($in);
            }
  } // operationGenerique


  /**
     * Obtient le nombre d'opérations effectuées depuis le démarrage
     * Utile pour le monitoring
     * @return Nombre d'appels reçus
     */
  public int getNombreOperations ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNombreOperations", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNombreOperations (        );
            } finally {
                _releaseReply ($in);
            }
  } // getNombreOperations


  /**
     * Réinitialise le compteur d'opérations
     */
  public void reinitialiserCompteur ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("reinitialiserCompteur", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                reinitialiserCompteur (        );
            } finally {
                _releaseReply ($in);
            }
  } // reinitialiserCompteur


  /**
     * Méthode de shutdown asynchrone (one-way)
     * N'attend pas de réponse du serveur
     * Arrête l'exécution du serveur proprement
     */
  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculatriceApp/Calculatrice:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CalculatriceStub
