package CalculatriceApp;


/**
* CalculatriceApp/_GestionnaireServeurStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Interface de gestion et monitoring
   * Permet de surveiller l'état du serveur
   */
public class _GestionnaireServeurStub extends org.omg.CORBA.portable.ObjectImpl implements CalculatriceApp.GestionnaireServeur
{


  /**
       * Obtient le timestamp du démarrage du serveur
       * @return Nombre de secondes depuis le démarrage (Unix timestamp)
       */
  public int getTimestampDemarrage ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTimestampDemarrage", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTimestampDemarrage (        );
            } finally {
                _releaseReply ($in);
            }
  } // getTimestampDemarrage


  /**
       * Obtient le statut du serveur
       * @return Message descriptif du statut
       */
  public String getStatut ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getStatut", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getStatut (        );
            } finally {
                _releaseReply ($in);
            }
  } // getStatut


  /**
       * Obtient la version de la calculatrice
       * @return Numéro de version (ex: "1.0.0")
       */
  public String getVersion ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getVersion", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getVersion (        );
            } finally {
                _releaseReply ($in);
            }
  } // getVersion

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculatriceApp/GestionnaireServeur:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "CalculatriceApp._GestionnaireServeurStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionnaireServeurStub
