package CalculatriceApp;


/**
* CalculatriceApp/_PdfServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 35 UTC
*/


/**
   * Interface principale PDF
   * Les entrées/sorties PDF sont transmises en base64 (string).
   */
public class _PdfServiceStub extends org.omg.CORBA.portable.ObjectImpl implements CalculatriceApp.PdfService
{


  /** Fusionne 2 PDFs (input1 + input2) -> pdfBase64Out */
  public CalculatriceApp.ResultatPdf fusionPdf (String pdfBase64_1, String pdfBase64_2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("fusionPdf", true);
                $out.write_string (pdfBase64_1);
                $out.write_string (pdfBase64_2);
                $in = _invoke ($out);
                CalculatriceApp.ResultatPdf $result = CalculatriceApp.ResultatPdfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return fusionPdf (pdfBase64_1, pdfBase64_2        );
            } finally {
                _releaseReply ($in);
            }
  } // fusionPdf


  /** Découpe un PDF en une nouvelle sortie contenant uniquement la plage */
  public CalculatriceApp.ResultatPdf decoupagePdf (String pdfBase64, CalculatriceApp.PlagePages plage)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("decoupagePdf", true);
                $out.write_string (pdfBase64);
                CalculatriceApp.PlagePagesHelper.write ($out, plage);
                $in = _invoke ($out);
                CalculatriceApp.ResultatPdf $result = CalculatriceApp.ResultatPdfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return decoupagePdf (pdfBase64, plage        );
            } finally {
                _releaseReply ($in);
            }
  } // decoupagePdf


  /** Extraction d'une page (plage d'une page) -> nouveau PDF */
  public CalculatriceApp.ResultatPdf extractionPage (String pdfBase64, CalculatriceApp.PlagePages plage)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractionPage", true);
                $out.write_string (pdfBase64);
                CalculatriceApp.PlagePagesHelper.write ($out, plage);
                $in = _invoke ($out);
                CalculatriceApp.ResultatPdf $result = CalculatriceApp.ResultatPdfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractionPage (pdfBase64, plage        );
            } finally {
                _releaseReply ($in);
            }
  } // extractionPage


  /** Suppression des pages (définies par plage) -> PDF résultat */
  public CalculatriceApp.ResultatPdf suppressionPage (String pdfBase64, CalculatriceApp.PlagePages plage)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("suppressionPage", true);
                $out.write_string (pdfBase64);
                CalculatriceApp.PlagePagesHelper.write ($out, plage);
                $in = _invoke ($out);
                CalculatriceApp.ResultatPdf $result = CalculatriceApp.ResultatPdfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return suppressionPage (pdfBase64, plage        );
            } finally {
                _releaseReply ($in);
            }
  } // suppressionPage


  /** Ajoute un mot de passe : protection du PDF en sortie */
  public CalculatriceApp.ResultatPdf ajoutMotDePasse (String pdfBase64, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajoutMotDePasse", true);
                $out.write_string (pdfBase64);
                $out.write_string (password);
                $in = _invoke ($out);
                CalculatriceApp.ResultatPdf $result = CalculatriceApp.ResultatPdfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajoutMotDePasse (pdfBase64, password        );
            } finally {
                _releaseReply ($in);
            }
  } // ajoutMotDePasse


  /** Convertit PDF -> image(s) (PNG)
     * Simplification TP : renvoie base64 du premier rendu (page 1).
     * Le champ nomFichierSortie contiendra par ex. "image1.png".
     */
  public CalculatriceApp.ResultatPdf conversionPdfEnImage (String pdfBase64, int dpi)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("conversionPdfEnImage", true);
                $out.write_string (pdfBase64);
                $out.write_long (dpi);
                $in = _invoke ($out);
                CalculatriceApp.ResultatPdf $result = CalculatriceApp.ResultatPdfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return conversionPdfEnImage (pdfBase64, dpi        );
            } finally {
                _releaseReply ($in);
            }
  } // conversionPdfEnImage


  /** Extrait le texte d'un PDF (retourne texte directement dans message + succes=true) */
  public CalculatriceApp.ResultatPdf extractionTexte (String pdfBase64)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extractionTexte", true);
                $out.write_string (pdfBase64);
                $in = _invoke ($out);
                CalculatriceApp.ResultatPdf $result = CalculatriceApp.ResultatPdfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extractionTexte (pdfBase64        );
            } finally {
                _releaseReply ($in);
            }
  } // extractionTexte


  /** Crée un PDF depuis un texte donné */
  public CalculatriceApp.ResultatPdf creationPdf (String texte)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creationPdf", true);
                $out.write_string (texte);
                $in = _invoke ($out);
                CalculatriceApp.ResultatPdf $result = CalculatriceApp.ResultatPdfHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creationPdf (texte        );
            } finally {
                _releaseReply ($in);
            }
  } // creationPdf

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculatriceApp/PdfService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PdfServiceStub
