package CalculatriceApp;


/**
* CalculatriceApp/Calculatrice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Interface principale : Calculatrice
   * 
   * Fournit des opérations mathématiques variées
   * sur deux nombres flottants
   */
public interface Calculatrice extends CalculatriceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculatrice
