package CalculatriceApp;


/**
* CalculatriceApp/CalculatricePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Interface principale : Calculatrice
   * 
   * Fournit des opérations mathématiques variées
   * sur deux nombres flottants
   */
public abstract class CalculatricePOA extends org.omg.PortableServer.Servant
 implements CalculatriceApp.CalculatriceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("substract", new java.lang.Integer (1));
    _methods.put ("multiply", new java.lang.Integer (2));
    _methods.put ("divide", new java.lang.Integer (3));
    _methods.put ("modulo", new java.lang.Integer (4));
    _methods.put ("power", new java.lang.Integer (5));
    _methods.put ("operationGenerique", new java.lang.Integer (6));
    _methods.put ("getNombreOperations", new java.lang.Integer (7));
    _methods.put ("reinitialiserCompteur", new java.lang.Integer (8));
    _methods.put ("shutdown", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /**
       * Effectue l'addition de deux nombres
       * @param a Premier opérande
       * @param b Deuxième opérande
       * @return Le résultat de a + b
       */
       case 0:  // CalculatriceApp/Calculatrice/add
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.add (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }


  /**
       * Effectue la soustraction
       * @param a Minuende
       * @param b Soustrahende
       * @return Le résultat de a - b
       */
       case 1:  // CalculatriceApp/Calculatrice/substract
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.substract (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }


  /**
       * Effectue la multiplication
       * @param a Premier facteur
       * @param b Deuxième facteur
       * @return Le résultat de a * b
       */
       case 2:  // CalculatriceApp/Calculatrice/multiply
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.multiply (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }


  /**
       * Effectue la division avec vérification
       * @param numerateur Dividende
       * @param denominateur Diviseur
       * @return Le résultat de numerateur / denominateur
       * @throws DivisionParZeroException si denominateur == 0
       */
       case 3:  // CalculatriceApp/Calculatrice/divide
       {
         try {
           double numerateur = in.read_double ();
           double denominateur = in.read_double ();
           double $result = (double)0;
           $result = this.divide (numerateur, denominateur);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (CalculatriceApp.DivisionParZeroException $ex) {
           out = $rh.createExceptionReply ();
           CalculatriceApp.DivisionParZeroExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
       * Calcule le modulo (reste de la division entière)
       * @param dividende Premier nombre
       * @param diviseur Deuxième nombre
       * @return Le reste de la division
       * @throws DivisionParZeroException si diviseur == 0
       */
       case 4:  // CalculatriceApp/Calculatrice/modulo
       {
         try {
           int dividende = in.read_long ();
           int diviseur = in.read_long ();
           int $result = (int)0;
           $result = this.modulo (dividende, diviseur);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (CalculatriceApp.DivisionParZeroException $ex) {
           out = $rh.createExceptionReply ();
           CalculatriceApp.DivisionParZeroExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
       * Calcule la puissance (base ^ exposant)
       * @param base La base
       * @param exposant L'exposant (doit être e 0)
       * @return base ^ exposant
       */
       case 5:  // CalculatriceApp/Calculatrice/power
       {
         double base = in.read_double ();
         int exposant = in.read_long ();
         double $result = (double)0;
         $result = this.power (base, exposant);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }


  /**
       * Opération générique avec type d'opération comme paramètre
       * Permet de tester différentes opérations dynamiquement
       * @param operation Le type d'opération à effectuer
       * @param a Premier opérande
       * @param b Deuxième opérande
       * @return Structure contenant le résultat et les métadonnées
       * @throws DivisionParZeroException si division par zéro
       * @throws OperationNonSupporteeException si opération invalide
       */
       case 6:  // CalculatriceApp/Calculatrice/operationGenerique
       {
         try {
           CalculatriceApp.TypeOperation operation = CalculatriceApp.TypeOperationHelper.read (in);
           double a = in.read_double ();
           double b = in.read_double ();
           CalculatriceApp.ResultatCalcul $result = null;
           $result = this.operationGenerique (operation, a, b);
           out = $rh.createReply();
           CalculatriceApp.ResultatCalculHelper.write (out, $result);
         } catch (CalculatriceApp.DivisionParZeroException $ex) {
           out = $rh.createExceptionReply ();
           CalculatriceApp.DivisionParZeroExceptionHelper.write (out, $ex);
         } catch (CalculatriceApp.OperationNonSupporteeException $ex) {
           out = $rh.createExceptionReply ();
           CalculatriceApp.OperationNonSupporteeExceptionHelper.write (out, $ex);
         }
         break;
       }


  /**
       * Obtient le nombre d'opérations effectuées depuis le démarrage
       * Utile pour le monitoring
       * @return Nombre d'appels reçus
       */
       case 7:  // CalculatriceApp/Calculatrice/getNombreOperations
       {
         int $result = (int)0;
         $result = this.getNombreOperations ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  /**
       * Réinitialise le compteur d'opérations
       */
       case 8:  // CalculatriceApp/Calculatrice/reinitialiserCompteur
       {
         this.reinitialiserCompteur ();
         out = $rh.createReply();
         break;
       }


  /**
       * Méthode de shutdown asynchrone (one-way)
       * N'attend pas de réponse du serveur
       * Arrête l'exécution du serveur proprement
       */
       case 9:  // CalculatriceApp/Calculatrice/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculatriceApp/Calculatrice:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calculatrice _this() 
  {
    return CalculatriceHelper.narrow(
    super._this_object());
  }

  public Calculatrice _this(org.omg.CORBA.ORB orb) 
  {
    return CalculatriceHelper.narrow(
    super._this_object(orb));
  }


} // class CalculatricePOA
