package CalculatriceApp;

/**
* CalculatriceApp/CalculatriceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Interface principale : Calculatrice
   * 
   * Fournit des opérations mathématiques variées
   * sur deux nombres flottants
   */
public final class CalculatriceHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.Calculatrice value = null;

  public CalculatriceHolder ()
  {
  }

  public CalculatriceHolder (CalculatriceApp.Calculatrice initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.CalculatriceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.CalculatriceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.CalculatriceHelper.type ();
  }

}
