package CalculatriceApp;


/**
* CalculatriceApp/CalculatriceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* jeudi 7 mai 2026 04 h 35 UTC
*/


/**
   * Interface principale : Calculatrice
   * 
   * Fournit des opérations mathématiques variées
   * sur deux nombres flottants
   */
public interface CalculatriceOperations 
{

  /**
     * Effectue l'addition de deux nombres
     * @param a Premier opérande
     * @param b Deuxième opérande
     * @return Le résultat de a + b
     */
  double add (double a, double b);

  /**
     * Effectue la soustraction
     * @param a Minuende
     * @param b Soustrahende
     * @return Le résultat de a - b
     */
  double substract (double a, double b);

  /**
     * Effectue la multiplication
     * @param a Premier facteur
     * @param b Deuxième facteur
     * @return Le résultat de a * b
     */
  double multiply (double a, double b);

  /**
     * Effectue la division avec vérification
     * @param numerateur Dividende
     * @param denominateur Diviseur
     * @return Le résultat de numerateur / denominateur
     * @throws DivisionParZeroException si denominateur == 0
     */
  double divide (double numerateur, double denominateur) throws CalculatriceApp.DivisionParZeroException;

  /**
     * Calcule le modulo (reste de la division entière)
     * @param dividende Premier nombre
     * @param diviseur Deuxième nombre
     * @return Le reste de la division
     * @throws DivisionParZeroException si diviseur == 0
     */
  int modulo (int dividende, int diviseur) throws CalculatriceApp.DivisionParZeroException;

  /**
     * Calcule la puissance (base ^ exposant)
     * @param base La base
     * @param exposant L'exposant (doit etre >= 0)
     * @return base ^ exposant
     */
  double power (double base, int exposant);

  /**
     * Opération générique avec type d'opération comme paramètre
     * Permet de tester différentes opérations dynamiquement
     * @param operation Le type d'opération à effectuer
     * @param a Premier opérande
     * @param b Deuxième opérande
     * @return Structure contenant le résultat et les métadonnées
     * @throws DivisionParZeroException si division par zéro
     * @throws OperationNonSupporteeException si opération invalide
     */
  CalculatriceApp.ResultatCalcul operationGenerique (CalculatriceApp.TypeOperation operation, double a, double b) throws CalculatriceApp.DivisionParZeroException, CalculatriceApp.OperationNonSupporteeException;

  /**
     * Obtient le nombre d'opérations effectuées depuis le démarrage
     * Utile pour le monitoring
     * @return Nombre d'appels reçus
     */
  int getNombreOperations ();

  /**
     * Réinitialise le compteur d'opérations
     */
  void reinitialiserCompteur ();

  /**
     * Méthode de shutdown asynchrone (one-way)
     * N'attend pas de réponse du serveur
     * Arrête l'exécution du serveur proprement
     */
  void shutdown ();
} // interface CalculatriceOperations
