package CalculatriceApp;


/**
* CalculatriceApp/DivisionParZeroException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/

public final class DivisionParZeroException extends org.omg.CORBA.UserException
{
  public String message = null;

  public DivisionParZeroException ()
  {
    super(DivisionParZeroExceptionHelper.id());
  } // ctor

  public DivisionParZeroException (String _message)
  {
    super(DivisionParZeroExceptionHelper.id());
    message = _message;
  } // ctor


  public DivisionParZeroException (String $reason, String _message)
  {
    super(DivisionParZeroExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class DivisionParZeroException
