package CalculatriceApp;


/**
* CalculatriceApp/GestionnaireServeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Interface de gestion et monitoring
   * Permet de surveiller l'état du serveur
   */
public interface GestionnaireServeur extends GestionnaireServeurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionnaireServeur
