package CalculatriceApp;

/**
* CalculatriceApp/GestionnaireServeurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Interface de gestion et monitoring
   * Permet de surveiller l'état du serveur
   */
public final class GestionnaireServeurHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.GestionnaireServeur value = null;

  public GestionnaireServeurHolder ()
  {
  }

  public GestionnaireServeurHolder (CalculatriceApp.GestionnaireServeur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.GestionnaireServeurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.GestionnaireServeurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.GestionnaireServeurHelper.type ();
  }

}
