package CalculatriceApp;


/**
* CalculatriceApp/GestionnaireServeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Interface de gestion et monitoring
   * Permet de surveiller l'état du serveur
   */
public interface GestionnaireServeurOperations 
{

  /**
       * Obtient le timestamp du démarrage du serveur
       * @return Nombre de secondes depuis le démarrage (Unix timestamp)
       */
  int getTimestampDemarrage ();

  /**
       * Obtient le statut du serveur
       * @return Message descriptif du statut
       */
  String getStatut ();

  /**
       * Obtient la version de la calculatrice
       * @return Numéro de version (ex: "1.0.0")
       */
  String getVersion ();
} // interface GestionnaireServeurOperations
