package CalculatriceApp;


/**
* CalculatriceApp/GestionnaireServeurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Interface de gestion et monitoring
   * Permet de surveiller l'état du serveur
   */
public abstract class GestionnaireServeurPOA extends org.omg.PortableServer.Servant
 implements CalculatriceApp.GestionnaireServeurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getTimestampDemarrage", new java.lang.Integer (0));
    _methods.put ("getStatut", new java.lang.Integer (1));
    _methods.put ("getVersion", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /**
       * Obtient le timestamp du démarrage du serveur
       * @return Nombre de secondes depuis le démarrage (Unix timestamp)
       */
       case 0:  // CalculatriceApp/GestionnaireServeur/getTimestampDemarrage
       {
         int $result = (int)0;
         $result = this.getTimestampDemarrage ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  /**
       * Obtient le statut du serveur
       * @return Message descriptif du statut
       */
       case 1:  // CalculatriceApp/GestionnaireServeur/getStatut
       {
         String $result = null;
         $result = this.getStatut ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
       * Obtient la version de la calculatrice
       * @return Numéro de version (ex: "1.0.0")
       */
       case 2:  // CalculatriceApp/GestionnaireServeur/getVersion
       {
         String $result = null;
         $result = this.getVersion ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculatriceApp/GestionnaireServeur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionnaireServeur _this() 
  {
    return GestionnaireServeurHelper.narrow(
    super._this_object());
  }

  public GestionnaireServeur _this(org.omg.CORBA.ORB orb) 
  {
    return GestionnaireServeurHelper.narrow(
    super._this_object(orb));
  }


} // class GestionnaireServeurPOA
