package CalculatriceApp;

/**
* CalculatriceApp/OperationNonSupporteeExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/

public final class OperationNonSupporteeExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.OperationNonSupporteeException value = null;

  public OperationNonSupporteeExceptionHolder ()
  {
  }

  public OperationNonSupporteeExceptionHolder (CalculatriceApp.OperationNonSupporteeException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.OperationNonSupporteeExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.OperationNonSupporteeExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.OperationNonSupporteeExceptionHelper.type ();
  }

}
