package CalculatriceApp;


/**
* CalculatriceApp/ResultatCalcul.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/

public final class ResultatCalcul implements org.omg.CORBA.portable.IDLEntity
{
  public double valeur = (double)0;

  // Le résultat numérique
  public String operationEffectuee = null;

  // Description de l'opération
  public int timestampUnix = (int)0;

  public ResultatCalcul ()
  {
  } // ctor

  public ResultatCalcul (double _valeur, String _operationEffectuee, int _timestampUnix)
  {
    valeur = _valeur;
    operationEffectuee = _operationEffectuee;
    timestampUnix = _timestampUnix;
  } // ctor

} // class ResultatCalcul
