package CalculatriceApp;


/**
* CalculatriceApp/ResultatCalculHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/

abstract public class ResultatCalculHelper
{
  private static String  _id = "IDL:CalculatriceApp/ResultatCalcul:1.0";

  public static void insert (org.omg.CORBA.Any a, CalculatriceApp.ResultatCalcul that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CalculatriceApp.ResultatCalcul extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[0] = new org.omg.CORBA.StructMember (
            "valeur",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "operationEffectuee",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "timestampUnix",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CalculatriceApp.ResultatCalculHelper.id (), "ResultatCalcul", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CalculatriceApp.ResultatCalcul read (org.omg.CORBA.portable.InputStream istream)
  {
    CalculatriceApp.ResultatCalcul value = new CalculatriceApp.ResultatCalcul ();
    value.valeur = istream.read_double ();
    value.operationEffectuee = istream.read_string ();
    value.timestampUnix = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CalculatriceApp.ResultatCalcul value)
  {
    ostream.write_double (value.valeur);
    ostream.write_string (value.operationEffectuee);
    ostream.write_long (value.timestampUnix);
  }

}
