package CalculatriceApp;

/**
* CalculatriceApp/TypeOperationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Énumération des opérations disponibles
   */
public final class TypeOperationHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculatriceApp.TypeOperation value = null;

  public TypeOperationHolder ()
  {
  }

  public TypeOperationHolder (CalculatriceApp.TypeOperation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatriceApp.TypeOperationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatriceApp.TypeOperationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatriceApp.TypeOperationHelper.type ();
  }

}
