package CalculatriceApp;


/**
* CalculatriceApp/TypeOperationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, April 29, 2026 8:27:15 AM UTC
*/


/**
   * Énumération des opérations disponibles
   */
abstract public class TypeOperationHelper
{
  private static String  _id = "IDL:CalculatriceApp/TypeOperation:1.0";

  public static void insert (org.omg.CORBA.Any a, CalculatriceApp.TypeOperation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CalculatriceApp.TypeOperation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (CalculatriceApp.TypeOperationHelper.id (), "TypeOperation", new String[] { "ADDITION", "SOUSTRACTION", "MULTIPLICATION", "DIVISION", "MODULO", "PUISSANCE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CalculatriceApp.TypeOperation read (org.omg.CORBA.portable.InputStream istream)
  {
    return CalculatriceApp.TypeOperation.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CalculatriceApp.TypeOperation value)
  {
    ostream.write_long (value.value ());
  }

}
